// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: queueservice.proto

package comms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueRequest) Reset() {
	*x = QueueRequest{}
	mi := &file_queueservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRequest) ProtoMessage() {}

func (x *QueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queueservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRequest.ProtoReflect.Descriptor instead.
func (*QueueRequest) Descriptor() ([]byte, []int) {
	return file_queueservice_proto_rawDescGZIP(), []int{0}
}

type QueueStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFront       bool                   `protobuf:"varint,1,opt,name=isFront,proto3" json:"isFront,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatus) Reset() {
	*x = QueueStatus{}
	mi := &file_queueservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatus) ProtoMessage() {}

func (x *QueueStatus) ProtoReflect() protoreflect.Message {
	mi := &file_queueservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatus.ProtoReflect.Descriptor instead.
func (*QueueStatus) Descriptor() ([]byte, []int) {
	return file_queueservice_proto_rawDescGZIP(), []int{1}
}

func (x *QueueStatus) GetIsFront() bool {
	if x != nil {
		return x.IsFront
	}
	return false
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_queueservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queueservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_queueservice_proto_rawDescGZIP(), []int{2}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_queueservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queueservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_queueservice_proto_rawDescGZIP(), []int{3}
}

var File_queueservice_proto protoreflect.FileDescriptor

const file_queueservice_proto_rawDesc = "" +
	"\n" +
	"\x12queueservice.proto\x12\x05comms\"\x0e\n" +
	"\fQueueRequest\"'\n" +
	"\vQueueStatus\x12\x18\n" +
	"\aisFront\x18\x01 \x01(\bR\aisFront\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse2\xc9\x01\n" +
	"\fQueueService\x129\n" +
	"\x0eIsFrontOfQueue\x12\x13.comms.QueueRequest\x1a\x12.comms.QueueStatus\x12A\n" +
	"\x14SubscribeQueueStatus\x12\x13.comms.QueueRequest\x1a\x12.comms.QueueStatus0\x01\x12;\n" +
	"\bShutdown\x12\x16.comms.ShutdownRequest\x1a\x17.comms.ShutdownResponseB&Z$github.com/morfien101/dynamo-q/commsb\x06proto3"

var (
	file_queueservice_proto_rawDescOnce sync.Once
	file_queueservice_proto_rawDescData []byte
)

func file_queueservice_proto_rawDescGZIP() []byte {
	file_queueservice_proto_rawDescOnce.Do(func() {
		file_queueservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_queueservice_proto_rawDesc), len(file_queueservice_proto_rawDesc)))
	})
	return file_queueservice_proto_rawDescData
}

var file_queueservice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_queueservice_proto_goTypes = []any{
	(*QueueRequest)(nil),     // 0: comms.QueueRequest
	(*QueueStatus)(nil),      // 1: comms.QueueStatus
	(*ShutdownRequest)(nil),  // 2: comms.ShutdownRequest
	(*ShutdownResponse)(nil), // 3: comms.ShutdownResponse
}
var file_queueservice_proto_depIdxs = []int32{
	0, // 0: comms.QueueService.IsFrontOfQueue:input_type -> comms.QueueRequest
	0, // 1: comms.QueueService.SubscribeQueueStatus:input_type -> comms.QueueRequest
	2, // 2: comms.QueueService.Shutdown:input_type -> comms.ShutdownRequest
	1, // 3: comms.QueueService.IsFrontOfQueue:output_type -> comms.QueueStatus
	1, // 4: comms.QueueService.SubscribeQueueStatus:output_type -> comms.QueueStatus
	3, // 5: comms.QueueService.Shutdown:output_type -> comms.ShutdownResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_queueservice_proto_init() }
func file_queueservice_proto_init() {
	if File_queueservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queueservice_proto_rawDesc), len(file_queueservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_queueservice_proto_goTypes,
		DependencyIndexes: file_queueservice_proto_depIdxs,
		MessageInfos:      file_queueservice_proto_msgTypes,
	}.Build()
	File_queueservice_proto = out.File
	file_queueservice_proto_goTypes = nil
	file_queueservice_proto_depIdxs = nil
}
